on:
  schedule: 
    - cron: '0 18 * * 6'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Update Script
        run: python getlist.py

      - name: Push to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Blacklist